# Generated by Django 3.0.8 on 2020-08-26 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='content',
        ),
    ]
