# Generated by Django 3.0.8 on 2020-09-09 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0008_comment_comment_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='article',
            new_name='word',
        ),
    ]
